### ISSUE TITLE
Feature: Pass current timestamp to wrapped component for purity

### ISSUE THREAD

**Issue by MilllerTime** [troch/react-timer-hoc#2]
I've been thinking about building a timer HoC, but found this one and it checks the boxes I really needed. The ability to change the tick delay dynamically is especially perfect. So, thanks a ton for this!

The exact component I had in mind had one main difference - it would pass down the current timestamp on each tick. I imagine many use cases, mine included, require doing something with the current time on each tick. The countdown example in your [demo](http://jsbin.com/nalixa/edit?html,js,output) even requires this.

It's of course easy to grab the current time on each render of the wrapped component, but this breaks purity. `new Date()`, `Date.now()`, etc. are impure functions and taint the call stack.

I realize this isn't a huge deal for the very simple countdown example, because the `timer()` HoC is the only state source that causes it to rerender. However, things get messier If the countdown is wrapped in another HoC, say `connect()` from react-redux. A higher-order rerender mid-tick might flash the value `15.7` briefly, which is an inconsistency of the countdown design. There are also other more complicated scenarios where impurity gets messy.

The easy fix for all of this is the add a `timestamp` property to the `timer` prop which is passed to the wrapped component. I'm happy to work on a PR, but wanted to run this by first.

I'm not attached to a unix timestamp from `Date.now()`. Other formats could be argued, such as an ISO 8601 formatted string from `new Date().toISOString()` or even just a native `Date` instance. However, I'm leaning towards using a timestamp from `Date.now()` simply because it doesn't require any object construction, and is useful as-is in many cases (such as the countdown).

Interested to hear your thoughts.

**Comment by troch** [comment]
That makes sense. I coincidentally had discussions at work today about introducing relative time formats in a component ("3 hours ago"). So yes please, a PR is welcome!

**Comment by MilllerTime** [comment]
Will do! Is passing down `Date.now()` good enough, or do I need to take into account `synchronizeWith` as well?

Btw, I use the fairly popular [react-timeago](https://www.npmjs.com/package/react-timeago) component for live updating relative times. It's also very smart about rerendering frequency. Only gotcha is you currently have to use version 3.2.0 instead of the latest 3.3.0 due to an outstanding [issue](https://github.com/nmn/react-timeago/issues/85).

**Comment by troch** [comment]
Date.now() should be good enough. `synchronizeWith`(if specified)  will call it at the right time.

**Comment by troch** [comment]
v2.2.0 published

**Comment by MilllerTime** [comment]
Thanks!
